on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  publish:
    name: publish
    runs-on: [dev]

    steps:
      - name: Install SSH Key
        run: |
          ssh-keyscan -H ${{ secrets.PROD_SSH_HOST }} > ~/.ssh/known_hosts
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Pull new service
        run: ssh ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} "cd ${{ secrets.PROD_REPO_DIR }} && git checkout main && git pull && exit"
